ComponentUT header and implement
NTUSTcs1091/Group6 pull request #23
Opened 2021-05-28 11:11 UTC by B-10515025

2021-05-31 11:21 UTC, harrisonyei requested changes
I commit some changes to the comments of both files.
Other than that, LGTM

2021-05-31 18:01 UTC, firewings2515 commented on src/Components/ComponentUT.h
> +    // Calculation weighted sum of input data
// Calculate weighted sum of input data

2021-05-31 18:03 UTC, firewings2515 commented on src/Components/ComponentUT.cpp
> +        // Calculation weighted sum in main thread
// Calculate weighted sum in main thread

2021-05-31 18:08 UTC, firewings2515 approved these changes
Fixed some grammar and format.
LGTM

2021-05-31 18:08 UTC, firewings2515 commented on src/Components/ComponentUT.cpp
> +    weighted_sum += *num * count++;
I'm not sure, but I think using parentheses to *num is better.
(e.i. (*num))

2021-06-01 06:02 UTC, AriaZhou approved these changes

2021-06-01 11:17 UTC, john0312 approved these changes

2021-06-01 11:17 UTC, john0312 commented on src/Components/ComponentUT.cpp
> +﻿// MIT License
Usually, the coding style specify tests files to be named as: something_test.cc
You can follow the coding style or have a consistent style for your project.

2021-06-01 11:17 UTC, john0312 commented on src/Components/ComponentUT.h
> +// MIT License
A header file is not needed for test usually, because we don't share symbols with other .cc files.

2021-06-05 07:16 UTC, john0312 commented on src/Components/ComponentUT.h
> +    // Calculation weighted sum of input data
This is a reasonable comment.

2021-06-18 05:38 UTC, merged